### ISSUE TITLE
Name of app, "gh-test", is hardcoded in template.

### ISSUE THREAD

**Issue by leoj3n** [donejs/donejs-feathers#21]
https://github.com/donejs/donejs-feathers/blob/4d8101439e14227d52cd9a48406d803a52181416/default/templates/framework-bootstrap/index.stache#L12-L17

**Comment by marshallswain** [comment]
Published to npm as version `0.1.1`

**Comment by marshallswain** [comment]
Oh, and thank you.  I found and fixed a TON more of these.
