### ISSUE TITLE
Can you clarify what is with canjs-feathers?

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/donejs-feathers#34]
I am not sure if this should not get adjusted to use the canjs-feathers project.

**Comment by frank-dspeed** [comment]
[https://github.com/canjs/canjs-feathers](https://github.com/canjs/canjs-feathers)

**Comment by frank-dspeed** [comment]
It looks overall more updated and new?

**Comment by marshallswain** [comment]
@frank-dspeed the canjs-feathers predates the can-connect-feathers project, which this `donejs-feathers` generator uses.  `canjs-feathers` will still work and give you the basic functionality that `can-connect` gives you with the same API, but I `can-connect-feathers` will be the more flexible project to work with.

**Comment by frank-dspeed** [comment]
can we put that information please into the canjs-feathers README.md? i think its more then importent. we should put it directly on top like 

# IMPORTENT
 the canjs-feathers predates the can-connect-feathers project, which this donejs-feathers generator uses. canjs-feathers will still work and give you the basic functionality that can-connect gives you with the same API, but I can-connect-feathers will be the more flexible project to work with.
